// 特殊字符 Ä ä Ö ö Ü ü ẞ ß é
// 由於專案改為分檔維護，載入時把此檔的詞彙推入 window.vocabParts
window.vocabParts = window.vocabParts || [];
window.vocabParts.push([
    // 名詞
    //{ type: 'noun', deutsch: '', chinese: '', gender: '', plural: '', Pl: '', countable: true, lesson: '', hint: '' },
    { type: 'noun', deutsch: 'Kaffee', chinese: '咖啡', gender: 'der', plural: 'Kaffees', Pl: '-s', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Tee', chinese: '茶', gender: 'der', plural: 'Tees', Pl: '-s', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Kakao', chinese: '可可飲', gender: 'der', plural: 'Kakaos', Pl: '-s', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Cappuccino', chinese: '卡布奇諾', gender: 'der', plural: 'Cappuccinos', Pl: '-s', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Espresso', chinese: '義式濃縮咖啡', gender: 'der', plural: 'Espressos', Pl: '-s', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Saft', chinese: '果汁', gender: 'der', plural: 'Säfte', Pl: '-:e', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Apfel', chinese: '蘋果', gender: 'der', plural: 'Äpfel', Pl: '-:', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Latte Macchiato', chinese: '焦糖瑪奇朵', gender: 'der', plural: 'Latte Macchiatos', Pl: '-s', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Apfelsaft', chinese: '蘋果汁', gender: 'der', plural: 'Apfelsäfte', Pl: '-:e', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Orangensaft', chinese: '橙汁', gender: 'der', plural: 'Orangensäfte', Pl: '-:e', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Eistee', chinese: '冰茶', gender: 'der', plural: 'Eistees', Pl: '-s', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Chai', chinese: '印度香料奶茶', gender: 'der', plural: 'Chais', Pl: '-s', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Milchkaffee', chinese: '拿鐵', gender: 'der', plural: 'Milchkaffees', Pl: '-s', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Wasser', chinese: '水', gender: 'das', countable: false, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Mineralwasser', chinese: '礦泉水', gender: 'das', plural: 'Mineralwasser', Pl: '-', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Eis', chinese: '冰', gender: 'das', countable: false, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Orange', chinese: '柳橙', gender: 'die', plural: 'Orangen', Pl: '-n', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Cola', chinese: '可樂', gender: 'die', plural: 'Colas', Pl: '-s', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Limonade', chinese: '汽水', gender: 'die', plural: 'Limonaden', Pl: '-n', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Milch', chinese: '(牛)奶', gender: 'die', countable: false, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Kellner', chinese: '侍者', gender: 'der', plural: 'Kellner', Pl: '-', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Kellnerin', chinese: '女侍者', gender: 'die', plural: 'Kellnerinnen', Pl: '-nen', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Zucker', chinese: '糖', gender: 'der', plural: 'Zucker', Pl: '-', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Getränk', chinese: '飲料', gender: 'das', plural: 'Getränke', Pl: '-e', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Portemonnaie', chinese: '錢夾', gender: 'das', plural: 'Portemonnaies', Pl: '-s', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Croissant', chinese: '牛角麵包 可頌', gender: 'das', plural: 'Croissants', Pl: '-s', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Brille', chinese: '眼鏡', gender: 'die', plural: 'Brillen', Pl: '-n', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Arbeitsplatz', chinese: '工作 場所/崗位/地點 職缺', gender: 'der', plural: 'Arbeitsplätze', Pl: '-:e', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Kopfhörer', chinese: '耳機', gender: 'der', plural: 'Kopfhörer', Pl: '-', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Café', chinese: '咖啡館', gender: 'das', plural: 'Cafés', Pl: '-s', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Marketing', chinese: '行銷學', gender: 'das', countable: false, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Glück', chinese: '幸福 幸運', gender: 'das', countable: false, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Restaurant', chinese: '餐廳', gender: 'das', plural: 'Restaurants', Pl: '-s', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Konzert', chinese: '音樂會 音樂廳', gender: 'das', plural: 'Konzerte', Pl: '-e', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Internet', chinese: '網路', gender: 'das', countable: false, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Atmosphäre', chinese: '氣氛', gender: 'die', plural: 'Atmosphären', Pl: '-n', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Leute', chinese: '人們', onlyplural: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Grafikdesigner', chinese: '平面設計師', gender: 'der', plural: 'Grafikdesigner', Pl: '-', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Grafikdesignerin', chinese: '女平面設計師', gender: 'die', plural: 'Grafikdesignerinnen', Pl: '-nen', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Lust', chinese: '興趣', gender: 'die', countable: false, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Band', chinese: '樂團', gender: 'die', plural: 'Bands', Pl: '-s', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Karte', chinese: '票 卡', gender: 'die', plural: 'Karten', Pl: '-n', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Bar', chinese: '酒吧', gender: 'die', plural: 'Bars', Pl: '-s', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Straße', chinese: '街道', gender: 'die', plural: 'Straßen', Pl: '-n', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Nachricht', chinese: '消息 訊息 新聞', gender: 'die', plural: 'Nachrichten', Pl: '-en', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Comic', chinese: '漫畫', gender: 'der', plural: 'Comics', Pl: '-s', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Euro', chinese: '歐元', gender: 'der', plural: 'Euros', Pl: '-s', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Cent', chinese: '歐分', gender: 'der', plural: 'Cents', Pl: '-s', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Gast', chinese: '客人', gender: 'der', plural: 'Gäste', Pl: '-:e', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Rechnung', chinese: '帳單', gender: 'die', plural: 'Rechnungen', Pl: '-en', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Hamburger', chinese: '漢堡 漢堡人 漢堡的', gender: 'der', plural: 'Hamburger', Pl: '-', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Fisch', chinese: '魚', gender: 'der', plural: 'Fische', Pl: '-e', countable: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Essen', chinese: '食物', gender: 'das', plural: 'Essen', Pl: '-', countable: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Sushi', chinese: '壽司', gender: 'das', plural: 'Sushis', Pl: '-s', countable: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Tier', chinese: '動物', gender: 'das', plural: 'Tiere', Pl: '-e', countable: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Fleisch', chinese: '肉', gender: 'das', countable: false, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Reise', chinese: '旅行', gender: 'die', plural: 'Reisen', Pl: '-n', countable: true, lesson: 'lesson 4', hint:'R-' },
    { type: 'noun', deutsch: 'Appetit', chinese: '胃口', gender: 'der', plural: 'Appetite', Pl: '-e', countable: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Blog', chinese: '部落格', gender: 'der', plural: 'Blogs', Pl: '-s', countable: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Blogger', chinese: '部落客', gender: 'der', plural: 'Blogger', Pl: '-', countable: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Food Blogger', chinese: '美食部落客', gender: 'der', plural: 'Food Blogger', Pl: '-', countable: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Mensch', chinese: '人', gender: 'der', plural: 'Menschen', Pl: '-en', countable: true, lesson: 'lesson 4', hint: 'M' },
    { type: 'noun', deutsch: 'Kommentar', chinese: '評論', gender: 'der', plural: 'Kommentare', Pl: '-e', countable: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Leben', chinese: '生活 人生 生命', gender: 'das', plural: 'Leben', Pl: '-', countable: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Thema', chinese: '主題 題材', gender: 'das', plural: 'Themen', Pl: '~men', countable: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Kultur', chinese: '文化', gender: 'die', plural: 'Kulturen', Pl: '-en', countable: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Musik', chinese: '音樂', gender: 'die', countable: false, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Käse', chinese: '乳酪', gender: 'der', plural: 'Käse', Pl: '-', countable: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Salat', chinese: '沙拉', gender: 'der', plural: 'Salate', Pl: '-e', countable: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Kartoffelsalat', chinese: '洋芋沙拉', gender: 'der', plural: 'Kartoffelsalate', Pl: '-e', countable: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Tofu', chinese: '豆腐', gender: 'der', countable: false, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Reis', chinese: '米', gender: 'der', countable: false, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Schinken', chinese: '火腿', gender: 'der', plural: 'Schinken', Pl: '-', countable: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Kuchen', chinese: '蛋糕', gender: 'der', plural: 'Kuchen', Pl: '-', countable: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Hunger', chinese: '飢餓', gender: 'der', countable: false, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Gericht', chinese: '菜餚', gender: 'das', plural: 'Gerichte', Pl: '-e', countable: true, lesson: 'lesson 4', hint: 'G' },
    { type: 'noun', deutsch: 'Rind', chinese: '牛', gender: 'das', plural: 'Rinder', Pl: '-er', countable: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Schwein', chinese: '豬', gender: 'das', plural: 'Schweine', Pl: '-e', countable: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Schweinfleisch', chinese: '豬肉', gender: 'das', countable: false, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Huhn', chinese: '母雞', gender: 'das', plural: 'Hühner', Pl: '-:er', countable: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Hähnchen', chinese: '小雞', gender: 'das', plural: 'Hähnchen', Pl: '-', countable: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Gemüse', chinese: '蔬菜', gender: 'das', plural: 'Gemüse', Pl: '-', countable: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Baguette', chinese: '法棍', gender: 'das', plural: 'Baguette', Pl: '-s', countable: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Hauptgericht', chinese: '主菜', gender: 'das', plural: 'Hauptgerichte', Pl: '-e', countable: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Steak', chinese: '牛排', gender: 'das', plural: 'Steaks', Pl: '-s', countable: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Schnitzel', chinese: '煎肉排', gender: 'das', plural: 'Schnitzel', Pl: '-', countable: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Gemüsecurry', chinese: '素咖哩', gender: 'das', plural: 'Gemüsecurrys', Pl: '-s', countable: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Speise', chinese: '菜餚', gender: 'die', plural: 'Speisen', Pl: '-n', countable: true, lesson: 'lesson 4', hint: 'S' },
    { type: 'noun', deutsch: 'Speisekarte', chinese: '菜單', gender: 'die', plural: 'Speisekarten', Pl: '-n', countable: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Vorspeise', chinese: '前菜', gender: 'die', plural: 'Vorspeisen', Pl: '-n', countable: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Tomate', chinese: '蕃茄', gender: 'die', plural: 'Tomaten', Pl: '-n', countable: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Kartoffel', chinese: '洋芋', gender: 'die', plural: 'Kartoffeln', Pl: '-n', countable: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Olive', chinese: '橄欖', gender: 'die', plural: 'Oliven', Pl: '-n', countable: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Suppe', chinese: '湯', gender: 'die', plural: 'Suppen', Pl: '-n', countable: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Tomatensuppe', chinese: '蕃茄湯', gender: 'die', plural: 'Tomatensuppen', Pl: '-n', countable: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Kartoffelsuppe', chinese: '洋芋湯', gender: 'die', plural: 'Kartoffelsuppen', Pl: '-n', countable: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Gemüsesuppe', chinese: '蔬菜湯', gender: 'die', plural: 'Gemüsesuppen', Pl: '-n', countable: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Nudel', chinese: '麵', gender: 'die', plural: 'Nudeln', Pl: '-n', countable: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Nudelsuppe', chinese: '湯麵', gender: 'die', plural: 'Nudelsuppen', Pl: '-n', countable: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Wurst', chinese: '香腸', gender: 'die', plural: 'Würste', Pl: '-:e', countable: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Currywurst', chinese: '咖哩香腸', gender: 'die', plural: 'Currywürste', Pl: '-:e', countable: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Schokolade', chinese: '巧克力', gender: 'die', plural: 'Schokoladen', Pl: '-n', countable: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Pizza', chinese: '比薩', gender: 'die', plural: 'Pizzen/Pizzas', Pl: '-s/~zen', countable: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Ananas', chinese: '鳳梨', gender: 'die', plural: 'Ananas/Ananasse', Pl: '-/-se', countable: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Idee', chinese: '主意', gender: 'die', plural: 'Ideen', Pl: '-n', countable: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Pommes Frites/Pommes', chinese: '炸薯條', onlyplural: true, lesson: 'lesson 4' },
    { type: 'noun', deutsch: 'Jahr', chinese: '年 歲', gender: 'das', plural: 'Jahre', Pl: '-e', countable: true, lesson: 'lesson 5' },
    { type: 'noun', deutsch: 'Monat', chinese: '月', gender: 'der', plural: 'Monate', Pl: '-e', countable: true, lesson: 'lesson 5' },
    { type: 'noun', deutsch: 'Tag', chinese: '天', gender: 'der', plural: 'Tage', Pl: '-e', countable: true, lesson: 'lesson 5' },
    { type: 'noun', deutsch: 'Stunde', chinese: '小時', gender: 'die', plural: 'Stunden', Pl: '-n', countable: true, lesson: 'lesson 5' },
    { type: 'noun', deutsch: 'Minute', chinese: '分鐘', gender: 'die', plural: 'Minuten', Pl: '-n', countable: true, lesson: 'lesson 5' },
    { type: 'noun', deutsch: 'Sekunde', chinese: '秒', gender: 'die', plural: 'Sekunden', Pl: '-n', countable: true, lesson: 'lesson 5' },
    { type: 'noun', deutsch: 'Woche', chinese: '星期', gender: 'die', plural: 'Wochen', Pl: '-n', countable: true, lesson: 'lesson 5' },
    { type: 'noun', deutsch: 'Wochentag', chinese: '星期的日子', gender: 'der', plural: 'Wochentage', Pl: '-e', countable: true, lesson: 'lesson 5' },
    { type: 'noun', deutsch: 'Montag', chinese: '周一', gender: 'der', plural: 'Montage', Pl: '-e', countable: true, lesson: 'lesson 5' },
    { type: 'noun', deutsch: 'Dienstag', chinese: '周二', gender: 'der', plural: 'Dienstage', Pl: '-e', countable: true, lesson: 'lesson 5' },
    { type: 'noun', deutsch: 'Mittwoch', chinese: '周三', gender: 'der', plural: 'Mittwoche', Pl: '-e', countable: true, lesson: 'lesson 5' },
    { type: 'noun', deutsch: 'Donnerstag', chinese: '周四', gender: 'der', plural: 'Donnerstage', Pl: '-e', countable: true, lesson: 'lesson 5' },
    { type: 'noun', deutsch: 'Freitag', chinese: '周五', gender: 'der', plural: 'Freitage', Pl: '-e', countable: true, lesson: 'lesson 5' },
    { type: 'noun', deutsch: 'Samstag', chinese: '周六', gender: 'der', plural: 'Samstage', Pl: '-e', countable: true, lesson: 'lesson 5' },
    { type: 'noun', deutsch: 'Sonntag', chinese: '周日', gender: 'der', plural: 'Sonntage', Pl: '-e', countable: true, lesson: 'lesson 5' },
    { type: 'noun', deutsch: 'Wochenende', chinese: '周末', gender: 'das', plural: 'Wochenenden', Pl: '-n', countable: true, lesson: 'lesson 5' },
    { type: 'noun', deutsch: 'Tageszeit', chinese: '一日時段', gender: 'die', plural: 'Tageszeiten', Pl: '-en', countable: true, lesson: 'lesson 5' },
    { type: 'noun', deutsch: 'Morgen', chinese: '早晨', gender: 'der', plural: 'Morgen', Pl: '-', countable: true, lesson: 'lesson 5' },
    { type: 'noun', deutsch: 'Vormittag', chinese: '上午', gender: 'der', plural: 'Vormittage', Pl: '-e', countable: true, lesson: 'lesson 5' },
    { type: 'noun', deutsch: 'Mittag', chinese: '中午', gender: 'der', plural: 'Mittage', Pl: '-e', countable: true, lesson: 'lesson 5' },
    { type: 'noun', deutsch: 'Nachmittag', chinese: '下午', gender: 'der', plural: 'Nachmittage', Pl: '-e', countable: true, lesson: 'lesson 5' },
    { type: 'noun', deutsch: 'Abend', chinese: '晚上', gender: 'der', plural: 'Abende', Pl: '-e', countable: true, lesson: 'lesson 5' },
    { type: 'noun', deutsch: 'Nacht', chinese: '深夜 半夜', gender: 'die', plural: 'Nächte', Pl: '-:e', countable: true, lesson: 'lesson 5' },
    { type: 'noun', deutsch: 'Uhr', chinese: '鐘 錶 (單數)鐘點 時刻', gender: 'die', plural: 'Uhren', Pl: '-en', countable: true, lesson: 'lesson 5'},
    { type: 'noun', deutsch: 'Viertel', chinese: '四分之一 一刻鐘', gender: 'das', plural: 'Viertel', Pl: '-', countable: true, lesson: 'lesson 5' },
    { type: 'noun', deutsch: 'Marathon', chinese: '馬拉松', gender: 'der', plural: 'Marathons', Pl: '-s', countable: true, lesson: 'lesson 5' },
    { type: 'noun', deutsch: 'Kilometer', chinese: '公里', gender: 'der', plural: 'Kilometer', Pl: '-', countable: true, lesson: 'lesson 5' },
    { type: 'noun', deutsch: 'Weltzeit', chinese: '世界時間', gender: 'die', plural: 'Weltzeiten', Pl: '-en', countable: true, lesson: 'lesson 5' },
    { type: 'noun', deutsch: 'Weltrekordzeit', chinese: '世界紀錄時間', gender: 'die', plural: 'Weltrekordzeiten', Pl: '-en', countable: true, lesson: 'lesson 5' },
    { type: 'noun', deutsch: 'Linie', chinese: '路線', gender: 'die', plural: 'Linien', Pl: '-n', countable: true, lesson: 'lesson 5' },
    { type: 'noun', deutsch: 'Test', chinese: '測驗 小考', gender: 'der', plural: 'Tests/Teste', Pl: '-s/-e', countable: true, lesson: 'lesson 5' },
    { type: 'noun', deutsch: 'Konferenz', chinese: '會議', gender: 'die', plural: 'Konferenzen', Pl: '-en', countable: true, lesson: 'lesson 5' },
    { type: 'noun', deutsch: 'Telefonkonferenz', chinese: '電話會議', gender: 'die', plural: 'Telefonkonferenzen', Pl: '-en', countable: true, lesson: 'lesson 5' },
    { type: 'noun', deutsch: 'Termin', chinese: '預約', gender: 'der', plural: 'Termine', Pl: '-e', countable: true, lesson: 'lesson 5' },
    { type: 'noun', deutsch: 'Terminproblem', chinese: '無法準時赴約', gender: 'das', plural: 'Terminproblem', Pl: '-e', countable: true, lesson: 'lesson 5' },
    { type: 'noun', deutsch: 'Fahrplan', chinese: '行車時刻表', gender: 'der', plural: 'Fahrpläne', Pl: '-:e', countable: true, lesson: 'lesson 5' },
    { type: 'noun', deutsch: 'Terminkalender', chinese: '行事曆', gender: 'der', plural: 'Terminkalender', Pl: '-', countable: true, lesson: 'lesson 5' },
    { type: 'noun', deutsch: 'Handy', chinese: '手機', gender: 'das', plural: 'Handys', Pl: '-s', countable: true, lesson: 'lesson 5' },
    { type: 'noun', deutsch: 'Paket', chinese: '包裹', gender: 'das', plural: 'Pakete', Pl: '-e', countable: true, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Computer', chinese: '電腦', gender: 'der', plural: 'Computer', Pl: '-', countable: true, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Brief', chinese: '信', gender: 'der', plural: 'Briefe', Pl: '-e', countable: true, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Training', chinese: '訓練', gender: 'das', countable: false, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Doktor', chinese: '博士 醫生', gender: 'der', plural: 'Doktoren', Pl: '-en', countable: true, lesson: 'lesson 5' },
    { type: 'noun', deutsch: 'Friseur/Frisor', chinese: '理髮師', gender: 'der', plural: 'Friseure/Frisore', Pl: '-e', countable: true, lesson: 'lesson 5' },
    { type: 'noun', deutsch: 'Friseurin/Frisorin', chinese: '女理髮師', gender: 'die', plural: 'Friseurinnen/Frisorinnen', Pl: '-nen', countable: true, lesson: 'lesson 5' },
    { type: 'noun', deutsch: 'Bäcker', chinese: '麵包師 烘培師', gender: 'der', plural: 'Bäcker', Pl: '-', countable: true, lesson: 'lesson 5' },
    { type: 'noun', deutsch: 'Bäckerin', chinese: '女麵包師 女烘培師', gender: 'die', plural: 'Bäckerinnen', Pl: '-nen', countable: true, lesson: 'lesson 5' },



    // 動詞
    //{ type: 'verb', infinitiv: '', ich: '', du: '', er: '', wir: '', ihr: '', sie: '', chinese: '', lesson: '', hint: '' },
    //{ type: 'konjunktiv', ich: '', du: '', er: '', wir: '', ihr: '', sie: '', chinese: '', lesson: '', hint: '' },
    { type: 'verb', infinitiv: 'trinken', ich: 'trinke', du: 'trinkst', er: 'trinkt', wir: 'trinken', ihr: 'trinkt', sie: 'trinken', chinese: '喝', lesson: 'lesson 3' },
    { type: 'verb', infinitiv: 'bestellen', ich: 'bestelle', du: 'bestellst', er: 'bestellt', wir: 'bestellen', ihr: 'bestellt', sie: 'bestellen', chinese: '點...飲料/食物', lesson: 'lesson 3' },
    { type: 'verb', infinitiv: 'nehmen', ich: 'nehme', du: 'nimmst', er: 'nimmt', wir: 'nehmen', ihr: 'nehmt', sie: 'nehmen', chinese: '喝... 吃... 搭乘...', lesson: 'lesson 3' },
    { type: 'konjunktiv', ich: 'möchte', du: 'möchtest', er: 'möchte', wir: 'möchten', ihr: 'möchtet', sie: 'möchten', chinese: '想要... 若有...多好', lesson: 'lesson 3', hint: 'm' },
    { type: 'verb', infinitiv: 'arbeiten', ich: 'arbeite', du: 'arbeitest', er: 'arbeitet', wir: 'arbeiten', ihr: 'arbeitet', sie: 'arbeiten', chinese: '工作', lesson: 'lesson 3' },
    { type: 'verb', infinitiv: 'studieren', ich: 'studiere', du: 'studierst', er: 'studiert', wir: 'studieren', ihr: 'studiert', sie: 'studieren', chinese: '上/念大學 讀...科系', lesson: 'lesson 3' },
    { type: 'verb', infinitiv: 'brauchen', ich: 'brauche', du: 'brauchst', er: 'braucht', wir: 'brauchen', ihr: 'braucht', sie: 'brauchen', chinese: '需要', lesson: 'lesson 3' },
    { type: 'verb', infinitiv: 'kennenlernen', ich: 'lerne kennen', du: 'lernst kennen', er: 'lernt kennen', wir: 'lernen kennen', ihr: 'lernt kennen', sie: 'lernen kennen', chinese: '結識 初次認識', lesson: 'lesson 3' },
    { type: 'verb', infinitiv: 'schicken', ich: 'schicke', du: 'schickst', er: 'schickt', wir: 'schicken', ihr: 'schickt', sie: 'schicken', chinese: '寄送... 發送...', lesson: 'lesson 3' },
    { type: 'verb', infinitiv: 'zahlen', ich: 'zahle', du: 'zahlst', er: 'zahlt', wir: 'zahlen', ihr: 'zahlt', sie: 'zahlen', chinese: '為...(事物)付帳 付...(多少)錢 付帳', lesson: 'lesson 3' },
    { type: 'verb', infinitiv: 'bezahlen', ich: 'bezahle', du: 'bezahlst', er: 'bezahlt', wir: 'bezahlen', ihr: 'bezahlt', sie: 'bezahlen', chinese: '為...(事物)付帳', lesson: 'lesson 3' },
    { type: 'verb', infinitiv: 'sehen', ich: 'sehe', du: 'siehst', er: 'sieht', wir: 'sehen', ihr: 'seht', sie: 'sehen', chinese: '看(見)', lesson: 'lesson 4' },
    { type: 'verb', infinitiv: 'aussehen', ich: 'sehe aus', du: 'siehst aus', er: 'sieht aus', wir: 'sehen aus', ihr: 'seht aus', sie: 'sehen aus', chinese: '看起來', lesson: 'lesson 4' },
    { type: 'verb', infinitiv: 'essen', ich: 'esse', du: 'isst', er: 'isst', wir: 'essen', ihr: 'esst', sie: 'essen', chinese: '吃', lesson: 'lesson 4' },
    { type: 'verb', infinitiv: 'fotografieren', ich: 'fotografiere', du: 'fotografierst', er: 'fotografiert', wir: 'fotografieren', ihr: 'fotografiert', sie: 'fotografieren', chinese: '攝影 拍...照片', lesson: 'lesson 4' },
    { type: 'verb', infinitiv: 'posten', ich: 'poste', du: 'postest', er: 'postet', wir: 'posten', ihr: 'postet', sie: 'posten', chinese: '公布 發送', lesson: 'lesson 4' },
    { type: 'verb', infinitiv: 'finden', ich: 'finde', du: 'findest', er: 'findet', wir: 'finden', ihr: 'findet', sie: 'finden', chinese: '覺得 認為', lesson: 'lesson 4' },
    { type: 'verb', infinitiv: 'nerven', ich: 'nerve', du: 'nervst', er: 'nervt', wir: 'nerven', ihr: 'nervt', sie: 'nerven', chinese: '煩', lesson: 'lesson 4' },
    { type: 'verb', er: 'stimmt', chinese: '正確 對', lesson: 'lesson 4' },
    { type: 'verb', infinitiv: 'glauben', ich: 'glaube', du: 'glaubst', er: 'glaubt', wir: 'glauben', ihr: 'glaubt', sie: 'glauben', chinese: '想... 認為... 覺得...', lesson: 'lesson 4' },
    { type: 'verb', infinitiv: 'wissen', ich: 'weiß', du: 'weißt', er: 'weiß', wir: 'wissen', ihr: 'wisst', sie: 'wissen', chinese: '知道', lesson: 'lesson 4' },
    { type: 'verb', infinitiv: 'fernsehen', ich: 'sehe fern', du: 'siehst fern', er: 'sieht fern', wir: 'sehen fern', ihr: 'seht fern', sie: 'sehen fern', chinese: '看電視', lesson: 'lesson 5' },
    { type: 'verb', infinitiv: 'stattfinden', er: 'findet statt', sie: 'finden statt', chinese: '舉行 舉辦', lesson: 'lesson 5' },
    { type: 'verb', infinitiv: 'ausfallen', er: 'fällt aus', sie: 'fallen aus', chinese: '取消 (停課 車停駛)', lesson: 'lesson 5' },
    { type: 'verb', infinitiv: 'wiederhören', chinese: '再聽', lesson: 'lesson 5' },
    { type: 'verb', infinitiv: 'tun', ich: 'tue', du: 'tust', er: 'tut', wir: 'tun', ihr: 'tut', sie: 'tun', chinese: '做... 有...效果 蒙受 遭受', lesson: 'lesson 5' },
    { type: 'verb', infinitiv: 'abfahren', ich: 'fahre ab', du: 'fährst ab', er: 'fährt ab', wir: 'fahren ab', ihr: 'fahrt ab', sie: 'fahren ab', chinese: '出發', lesson: 'lesson 5' },
    { type: 'verb', infinitiv: 'abholen', ich: 'hole ab', du: 'holst ab', er: 'holt ab', wir: 'holen ab', ihr: 'holt ab', sie: 'holen ab', chinese: '接...人 提領...物', lesson: 'lesson 5' },
    { type: 'verb', infinitiv: 'anrufen', ich: 'rufe an', du: 'rufst an', er: 'ruft an', wir: 'rufen an', ihr: 'ruft an', sie: 'rufen an', chinese: '打電話給...', lesson: 'lesson 5' },
    { type: 'verb', infinitiv: 'einkaufen', ich: 'kaufe ein', du: 'kaufst ein', er: 'kauft ein', wir: 'kaufen ein', ihr: 'kauft ein', sie: 'kaufen ein', chinese: '採買 購物', lesson: 'lesson 5' },
    { type: 'verb', infinitiv: 'schlafen', ich: 'schlafe', du: 'schläfst', er: 'schläft', wir: 'schlafen', ihr: 'schlafet', sie: 'schlafen', chinese: '睡覺', lesson: 'lesson 5' },
    { type: 'verb', infinitiv: 'ausschlafen', ich: 'schlafe aus', du: 'schläfst aus', er: 'schläft aus', wir: 'schlafen aus', ihr: 'schlaft aus', sie: 'schlafen aus', chinese: '補眠 睡飽', lesson: 'lesson 5' },
    { type: 'verb', infinitiv: 'ausschalten', ich: 'schalte aus', du: 'schaltest aus', er: 'schaltet aus', wir: 'schalten aus', ihr: 'schaltet aus', sie: 'schalten aus', chinese: '關...電源', lesson: 'lesson 5' },
    { type: 'verb', infinitiv: 'passen', ich: 'passe', du: 'passt', er: 'passt', wir: 'passen', ihr: 'passt', sie: 'passen', chinese: '適合 合宜', lesson: 'lesson 5' },
    { type: 'konjunktiv', ich: 'hätte', du: 'hättest', er: 'hätte', wir: 'hätten', ihr: 'hättet', sie: 'hätten', chinese: '若有...多好 想要有', lesson: 'lesson 5', hint: 'h' },
    { type: 'verb', er: 'freihaben', chinese: '放假 不上班', lesson: 'lesson 5' },


    // 形容詞
    //{ type: 'adjective', deutsch: '', chinese: '', lesson: '' },
    { type: 'adjective', deutsch: 'schwarz', chinese: '黑的', lesson: 'lesson 3' },
    { type: 'adjective', deutsch: 'in', chinese: '流行的 夯的', lesson: 'lesson 3' },
    { type: 'adjective', deutsch: 'toll', chinese: '讚的 棒的', lesson: 'lesson 3', hint: 't' },
    { type: 'adjective', deutsch: 'einfach', chinese: '簡單 容易的', lesson: 'lesson 3' },
    { type: 'adjective', deutsch: 'lecker', chinese: '可口的', lesson: 'lesson 3' },
    { type: 'adjective', deutsch: 'perfekt', chinese: '妥當 搞定的 完美的', lesson: 'lesson 3' },
    { type: 'adjective', deutsch: 'getrennt', chinese: '分開的', lesson: 'lesson 3' },
    { type: 'adjective', deutsch: 'total', chinese: '全部的 全然地', lesson: 'lesson 3' },
    { type: 'adjective', deutsch: 'teuer', chinese: '貴的', lesson: 'lesson 3' },
    { type: 'adjective', deutsch: 'vegetarisch', chinese: '素食的 素的', lesson: 'lesson 4' },
    { type: 'adjective', deutsch: 'süß', chinese: '甜的 甜美的', lesson: 'lesson 4' },
    { type: 'adjective', deutsch: 'andere', chinese: '其它的', lesson: 'lesson 4' },
    { type: 'adjective', deutsch: 'interessant', chinese: '有趣的', lesson: 'lesson 4' },
    { type: 'adjective', deutsch: 'scharf', chinese: '辣的', lesson: 'lesson 4' },
    { type: 'adjective', deutsch: 'alt', chinese: '老的 舊的', lesson: 'lesson 5' },
    { type: 'adjective', deutsch: 'spät', chinese: '晚的', lesson: 'lesson 5' },
    { type: 'adjective', deutsch: 'früh', chinese: '早的', lesson: 'lesson 5' },
    { type: 'adjective', deutsch: 'halb', chinese: '半的', lesson: 'lesson 5' },
    { type: 'adjective', deutsch: 'leid', chinese: '婉惜 遺憾 抱歉', lesson: 'lesson 5' },
    { type: 'adjective', deutsch: 'frei', chinese: '空的 有空的 放假的', lesson: 'lesson 5' },
    { type: 'adjective', deutsch: 'prima', chinese: '讚的 棒的', lesson: 'lesson 5', hint: 'p' },

    // 副詞
    //{ type: 'adverb', deutsch: '', chinese: '', lesson: '' },
    { type: 'adverb', deutsch: 'lieber', chinese: '寧願 比較喜歡', lesson: 'lesson 3' },
    { type: 'adverb', deutsch: 'überall', chinese: '到處', lesson: 'lesson 3' },
    { type: 'adverb', deutsch: 'super', chinese: '讚 棒地', lesson: 'lesson 3', hint: '副詞' },
    { type: 'adverb', deutsch: 'später', chinese: '晚些 稍晚', lesson: 'lesson 3' },
    { type: 'adverb', deutsch: 'gleich', chinese: '立刻 馬上', lesson: 'lesson 3' },
    { type: 'adverb', deutsch: 'heute', chinese: '今天', lesson: 'lesson 3' },
    { type: 'adverb', deutsch: 'morgen', chinese: '明天', lesson: 'lesson 3' },
    { type: 'adverb', deutsch: 'zusammen', chinese: '一起', lesson: 'lesson 3' },
    { type: 'adverb', deutsch: 'zurück', chinese: '返回 歸還 找回(錢)', lesson: 'lesson 3' },

    { type: 'adverb', deutsch: 'doch', chinese: '(強調語詞)', lesson: 'lesson 4' },
    { type: 'adverb', deutsch: 'pro', chinese: '贊成', lesson: 'lesson 4' },
    { type: 'adverb', deutsch: 'kontra', chinese: '反對', lesson: 'lesson 4' },
    { type: 'adverb', deutsch: 'fast', chinese: '幾乎 差不多', lesson: 'lesson 4' },
    { type: 'adverb', deutsch: 'vielleicht', chinese: '也許 或許', lesson: 'lesson 4' },
    { type: 'adverb', deutsch: 'leider', chinese: '可惜 遺憾地', lesson: 'lesson 5' },

    // 疑問詞
    //{ type: 'question', deutsch: '', chinese: '', lesson: '' },
    { type: 'question', deutsch: 'warum', chinese: '為什麼?', lesson: 'lesson 3' },
    { type: 'question', deutsch: 'wann', chinese: '何時?', lesson: 'lesson 4' },

    // 其他(人稱代名詞 介係詞 連接詞 所有格冠詞)
    { type: 'other', deutsch: 'mit', chinese: '有... 和... 加...', lesson: 'lesson 3' },
    { type: 'other', deutsch: 'ohne', chinese: '無... 去(不加)...', lesson: 'lesson 3' },
    { type: 'other', deutsch: 'von', chinese: '...的(所有格)', lesson: 'lesson 3' },
    { type: 'other', deutsch: 'wie', chinese: '如同 正如', lesson: 'lesson 3', hint: '連接詞' },
    { type: 'other', deutsch: 'als', chinese: '作為', lesson: 'lesson 3' },
    { type: 'other', deutsch: 'bis', chinese: '至', lesson: 'lesson 3' },
    { type: 'other', deutsch: 'für', chinese: '贊成的 對...而言 為了...', lesson: 'lesson 3' },
    { type: 'other', deutsch: 'alles', chinese: '所有東西 一切事物', lesson: 'lesson 4' },
    { type: 'other', deutsch: 'vor', chinese: '在...時間之前', lesson: 'lesson 5' },
    { type: 'other', deutsch: 'nach', chinese: '在...時間之後', lesson: 'lesson 5' },
    { type: 'other', deutsch: 'kurz', chinese: '短的(差三分鐘)', lesson: 'lesson 5' },

    // 片語
    //{ type: 'phrase', deutsch: '', chinese: '', lesson: '' },
    { type: 'phrase', deutsch: 'Kaffee schwarz', chinese: '黑咖啡', lesson: 'lesson 3' },
    { type: 'phrase', deutsch: 'so wie', chinese: '如同', lesson: 'lesson 3' },
    { type: 'phrase', deutsch: 'bis dann', chinese: '回頭見! 稍後見!', lesson: 'lesson 3', hint: 'd-' },
    { type: 'phrase', deutsch: 'bis gleich', chinese: '一會兒見!', lesson: 'lesson 3', hint: 'g-' },
    { type: 'phrase', deutsch: 'bis später', chinese: '稍後見!', lesson: 'lesson 3', hint: 's-' },
    { type: 'phrase', deutsch: 'bis morgen', chinese: '明天見!', lesson: 'lesson 3' },
    { type: 'phrase', deutsch: 'noch einmal', chinese: '再一次', lesson: 'lesson 4' },
    { type: 'phrase', deutsch: 'Guten Appetit', chinese: '用餐愉快', lesson: 'lesson 4' },


    // 國家 語言 城市(名詞)
    { type: 'country', deutsch: 'Indien', chinese: '印度', countable: false, lesson: 'lesson 3' }
]);