// 特殊字符 Ä ä Ö ö Ü ü ẞ ß é
// 由於專案改為分檔維護，載入時把此檔的詞彙推入 window.vocabParts
window.vocabParts = window.vocabParts || [];
window.vocabParts.push([
    // 名詞
    //{ type: 'noun', deutsch: '', chinese: '', gender: '', plural: '', Pl: '', countable: true, lesson: '', hint: '' },
    { type: 'noun', deutsch: 'Kaffee', chinese: '咖啡', gender: 'der', plural: 'Kaffees', Pl: '-s', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Tee', chinese: '茶', gender: 'der', plural: 'Tees', Pl: '-s', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Kakao', chinese: '可可飲', gender: 'der', plural: 'Kakaos', Pl: '-s', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Cappuccino', chinese: '卡布奇諾', gender: 'der', plural: 'Cappuccinos', Pl: '-s', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Espresso', chinese: '義式濃縮咖啡', gender: 'der', plural: 'Espressos', Pl: '-s', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Saft', chinese: '果汁', gender: 'der', plural: 'Säfte', Pl: '-:e', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Apfel', chinese: '蘋果', gender: 'der', plural: 'Äpfel', Pl: '-:', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Latte Macchiato', chinese: '焦糖瑪奇朵', gender: 'der', plural: 'Latte Macchiatos', Pl: '-s', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Apfelsaft', chinese: '蘋果汁', gender: 'der', plural: 'Apfelsäfte', Pl: '-:e', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Orangensaft', chinese: '橙汁', gender: 'der', plural: 'Orangensäfte', Pl: '-:e', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Eistee', chinese: '冰茶', gender: 'der', plural: 'Eistees', Pl: '-s', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Chai', chinese: '印度香料奶茶', gender: 'der', plural: 'Chais', Pl: '-s', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Milchkaffee', chinese: '拿鐵', gender: 'der', plural: 'Milchkaffees', Pl: '-s', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Wasser', chinese: '水', gender: 'das', countable: false, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Mineralwasser', chinese: '礦泉水', gender: 'das', plural: 'Mineralwasser', Pl: '-', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Eis', chinese: '冰', gender: 'das', countable: false, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Orange', chinese: '柳橙', gender: 'die', plural: 'Orangen', Pl: '-n', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Cola', chinese: '可樂', gender: 'die', plural: 'Colas', Pl: '-s', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Limonade', chinese: '汽水', gender: 'die', plural: 'Limonaden', Pl: '-n', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Milch', chinese: '(牛)奶', gender: 'die', countable: false, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Kellner', chinese: '侍者', gender: 'der', plural: 'Kellner', Pl: '-', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Kellnerin', chinese: '女侍者', gender: 'die', plural: 'Kellnerinnen', Pl: '-nen', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Zucker', chinese: '糖', gender: 'der', plural: 'Zucker', Pl: '-', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Getränk', chinese: '飲料', gender: 'das', plural: 'Getränke', Pl: '-e', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Portemonnaie', chinese: '錢夾', gender: 'das', plural: 'Portemonnaies', Pl: '-s', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Croissant', chinese: '牛角麵包 可頌', gender: 'das', plural: 'Croissants', Pl: '-s', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Brille', chinese: '眼鏡', gender: 'die', plural: 'Brillen', Pl: '-n', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Arbeitsplatz', chinese: '工作 場所/崗位/地點 職缺', gender: 'der', plural: 'Arbeitsplätze', Pl: '-:e', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Park', chinese: '公園', gender: 'der', plural: 'Parks', Pl: '-s', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Kopfhörer', chinese: '耳機', gender: 'der', plural: 'Kopfhörer', Pl: '-', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Café', chinese: '咖啡館', gender: 'das', plural: 'Cafés', Pl: '-s', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Marketing', chinese: '行銷學', gender: 'das', countable: false, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Glück', chinese: '幸福 幸運', gender: 'das', countable: false, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Restaurant', chinese: '餐廳', gender: 'das', plural: 'Restaurants', Pl: '-s', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Konzert', chinese: '音樂會 音樂廳', gender: 'das', plural: 'Konzerte', Pl: '-e', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Internet', chinese: '網路', gender: 'das', countable: false, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Atmosphäre', chinese: '氣氛', gender: 'die', plural: 'Atmosphären', Pl: '-n', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Leute', chinese: '人們', onlyplural: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Grafikdesigner', chinese: '平面設計師', gender: 'der', plural: 'Grafikdesigner', Pl: '-', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Grafikdesignerin', chinese: '女平面設計師', gender: 'die', plural: 'Grafikdesignerinnen', Pl: '-nen', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Abend', chinese: '晚上', gender: 'der', plural: 'Abende', Pl: '-e', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Lust', chinese: '興趣', gender: 'die', countable: false, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Band', chinese: '樂團', gender: 'die', plural: 'Bands', Pl: '-s', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Karte', chinese: '票 卡', gender: 'die', plural: 'Karten', Pl: '-n', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Bar', chinese: '酒吧', gender: 'die', plural: 'Bars', Pl: '-s', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Straße', chinese: '街道', gender: 'die', plural: 'Straßen', Pl: '-n', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Nachricht', chinese: '消息 訊息 新聞', gender: 'die', plural: 'Nachrichten', Pl: '-en', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Comic', chinese: '漫畫', gender: 'der', plural: 'Comics', Pl: '-s', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Euro', chinese: '歐元', gender: 'der', plural: 'Euros', Pl: '-s', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Cent', chinese: '歐分', gender: 'der', plural: 'Cents', Pl: '-s', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Gast', chinese: '客人', gender: 'der', plural: 'Gäste', Pl: '-:e', countable: true, lesson: 'lesson 3' },
    { type: 'noun', deutsch: 'Rechnung', chinese: '帳單', gender: 'die', plural: 'Rechnungen', Pl: '-en', countable: true, lesson: 'lesson 3' },


    // 動詞
    //{ type: 'verb', infinitiv: '', ich: '', du: '', er: '', wir: '', ihr: '', sie: '', chinese: '', lesson: '', hint: '' },
    //{ type: 'konjunktiv', ich: '', du: '', er: '', wir: '', ihr: '', sie: '', chinese: '', lesson: '', hint: '' },
    { type: 'verb', infinitiv: 'trinken', ich: 'trinke', du: 'trinkst', er: 'trinkt', wir: 'trinken', ihr: 'trinkt', sie: 'trinken', chinese: '喝', lesson: 'lesson 3' },
    { type: 'verb', infinitiv: 'bestellen', ich: 'bestelle', du: 'bestellst', er: 'bestellt', wir: 'bestellen', ihr: 'bestellt', sie: 'bestellen', chinese: '點...飲料/食物', lesson: 'lesson 3' },
    { type: 'verb', infinitiv: 'nehmen', ich: 'nehme', du: 'nimmst', er: 'nimmt', wir: 'nehmen', ihr: 'nehmt', sie: 'nehmen', chinese: '喝... 吃...', lesson: 'lesson 3' },
    { type: 'konjunktiv', ich: 'möchte', du: 'möchtest', er: 'möchte', wir: 'möchten', ihr: 'möchtet', sie: 'möchten', chinese: '想要... 若有...多好', lesson: 'lesson 3' },
    { type: 'verb', infinitiv: 'arbeiten', ich: 'arbeite', du: 'arbeitest', er: 'arbeitet', wir: 'arbeiten', ihr: 'arbeitet', sie: 'arbeiten', chinese: '工作', lesson: 'lesson 3' },
    { type: 'verb', infinitiv: 'studieren', ich: 'studiere', du: 'studierst', er: 'studiert', wir: 'studieren', ihr: 'studiert', sie: 'studieren', chinese: '上/念大學 讀...科系', lesson: 'lesson 3' },
    { type: 'verb', infinitiv: 'brauchen', ich: 'brauche', du: 'brauchst', er: 'braucht', wir: 'brauchen', ihr: 'braucht', sie: 'brauchen', chinese: '需要', lesson: 'lesson 3' },
    { type: 'verb', infinitiv: 'gehen', ich: 'gehe', du: 'gehst', er: 'geht', wir: 'gehen', ihr: 'geht', sie: 'gehen', chinese: '去... 離開 走了', lesson: 'lesson 3' },
    { type: 'verb', infinitiv: 'kennen', ich: 'kenne', du: 'kennst', er: 'kennt', wir: 'kennen', ihr: 'kennt', sie: 'kennen', chinese: '認識(知道)', lesson: 'lesson 3' },
    { type: 'verb', infinitiv: 'kennenlernen', ich: 'lerne kennen', du: 'lernst kennen', er: 'lernt kennen', wir: 'lernen kennen', ihr: 'lernt kennen', sie: 'lernen kennen', chinese: '結識 初次認識', lesson: 'lesson 3' },
    { type: 'verb', infinitiv: 'schicken', ich: 'schicke', du: 'schickst', er: 'schickt', wir: 'schicken', ihr: 'schickt', sie: 'schicken', chinese: '寄送... 發送...', lesson: 'lesson 3' },
    { type: 'verb', infinitiv: 'zahlen', ich: 'zahle', du: 'zahlst', er: 'zahlt', wir: 'zahlen', ihr: 'zahlt', sie: 'zahlen', chinese: '為...(事物)付帳 付...(多少)錢 付帳', lesson: 'lesson 3' },
    { type: 'verb', infinitiv: 'bezahlen', ich: 'bezahle', du: 'bezahlst', er: 'bezahlt', wir: 'bezahlen', ihr: 'bezahlt', sie: 'bezahlen', chinese: '為...(事物)付帳', lesson: 'lesson 3' },
    
    // 形容詞
    //{ type: 'adjective', deutsch: '', chinese: '', lesson: '' },
    { type: 'adjective', deutsch: 'schwarz', chinese: '黑的', lesson: 'lesson 3' },
    { type: 'adjective', deutsch: 'in', chinese: '流行的 夯的', lesson: 'lesson 3' },
    { type: 'adjective', deutsch: 'toll', chinese: '讚的 棒的', lesson: 'lesson 3', hint: '形容詞' },
    { type: 'adjective', deutsch: 'einfach', chinese: '簡單 容易的', lesson: 'lesson 3' },
    { type: 'adjective', deutsch: 'lecker', chinese: '可口的', lesson: 'lesson 3' },
    { type: 'adjective', deutsch: 'perfekt', chinese: '妥當 搞定的 完美的', lesson: 'lesson 3' },
    { type: 'adjective', deutsch: 'später', chinese: '晚些 稍晚', lesson: 'lesson 3' },
    { type: 'adjective', deutsch: 'getrennt', chinese: '分開的', lesson: 'lesson 3' },

    // 副詞
    //{ type: 'adverb', deutsch: '', chinese: '', lesson: '' },
    { type: 'adverb', deutsch: 'lieber', chinese: '寧願 比較喜歡', lesson: 'lesson 3' },
    { type: 'adverb', deutsch: 'überall', chinese: '到處', lesson: 'lesson 3' },
    { type: 'adverb', deutsch: 'hier', chinese: '這裡', lesson: 'lesson 3' },
    { type: 'adverb', deutsch: 'dort', chinese: '那裡', lesson: 'lesson 3' },
    { type: 'adverb', deutsch: 'super', chinese: '讚 棒地', lesson: 'lesson 3', hint: '副詞' },
    { type: 'adverb', deutsch: 'dann', chinese: '然後', lesson: 'lesson 3' },
    { type: 'adverb', deutsch: 'gleich', chinese: '立刻 馬上', lesson: 'lesson 3' },
    { type: 'adverb', deutsch: 'heute', chinese: '今天', lesson: 'lesson 3' },
    { type: 'adverb', deutsch: 'morgen', chinese: '明天', lesson: 'lesson 3' },
    { type: 'adverb', deutsch: 'zusammen', chinese: '一起', lesson: 'lesson 3' },
    { type: 'adverb', deutsch: 'zurück', chinese: '返回 歸還 找回(錢)', lesson: 'lesson 3' },

    // 疑問詞
    //{ type: 'question', deutsch: '', chinese: '', lesson: '' },
    { type: 'question', deutsch: 'warum', chinese: '為什麼?', lesson: 'lesson 3' },

    // 其他(人稱代名詞 介係詞 連接詞 所有格冠詞)
    { type: 'other', deutsch: 'mit', chinese: '有... 和... 加...', lesson: 'lesson 3' },
    { type: 'other', deutsch: 'ohne', chinese: '無... 去(不加)...', lesson: 'lesson 3' },
    { type: 'other', deutsch: 'von', chinese: '...的(所有格)', lesson: 'lesson 3' },
    { type: 'other', deutsch: 'wie', chinese: '如同 正如', lesson: 'lesson 3', hint: '連接詞' },
    { type: 'other', deutsch: 'als', chinese: '作為', lesson: 'lesson 3' },
    { type: 'other', deutsch: 'bis', chinese: '至', lesson: 'lesson 3' },

    // 片語
    //{ type: 'phrase', deutsch: '', chinese: '', lesson: '' },
    { type: 'phrase', deutsch: 'Kaffee schwarz', chinese: '黑咖啡', lesson: 'lesson 3' },
    { type: 'phrase', deutsch: 'so wie', chinese: '如同', lesson: 'lesson 3' },
    { type: 'phrase', deutsch: 'bis dann', chinese: '回頭見! 稍後見!', lesson: 'lesson 3', hint: 'd-' },
    { type: 'phrase', deutsch: 'bis gleich', chinese: '一會兒見!', lesson: 'lesson 3', hint: 'g-' },
    { type: 'phrase', deutsch: 'bis später', chinese: '稍後見!', lesson: 'lesson 3', hint: 's-' },
    { type: 'phrase', deutsch: 'bis morgen', chinese: '明天見!', lesson: 'lesson 3' },

    // 國家 語言 城市(名詞)
    { type: 'country', deutsch: 'Indien', chinese: '印度', countable: false, lesson: 'lesson 3' }
]);