// 特殊字符 Ä ä Ö ö Ü ü ẞ ß
// 由於專案改為分檔維護，載入時把此檔的詞彙推入 window.vocabParts
window.vocabParts = window.vocabParts || [];
window.vocabParts.push([
    // 名詞
    //{ type: 'noun', deutsch: '', chinese: '', gender: '', plural: '', Pl: '', countable: false/true, lesson: '', hint: '' },
    { type: 'noun', deutsch: 'Kursraum', chinese: '教室', gender: 'der', plural: 'Kursräume', Pl: '-:e', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Tisch', chinese: '桌', gender: 'der', plural: 'Tische', Pl: '-e', countable: true, lesson: 'lesson 0' },
/**/{ type: 'noun', deutsch: 'Stuhl', chinese: '椅', gender: 'der', plural: 'Stühle', Pl: '-:e', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Kuli', chinese: '原子筆', gender: 'der', plural: 'Kulis', Pl: '-s', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Stift', chinese: '筆', gender: 'der', plural: 'Stifte', Pl: '-e', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Bleistift', chinese: '鉛筆', gender: 'der', plural: 'Bleistifte', Pl: '-e', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Gegenstand', chinese: '東西 物件', gender: 'der', plural: 'Gegenstände', Pl: '-:e', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Text', chinese: '文章', gender: 'der', plural: 'Texte', Pl: '-e', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Marker', chinese: '馬克筆', gender: 'der', plural: 'Marker', Pl: '-', countable: true, lesson: 'lesson 0', hint: 'M' },
    { type: 'noun', deutsch: 'Textmarker', chinese: '馬克筆', gender: 'der', plural: 'Textmarker', Pl: '-', countable: true, lesson: 'lesson 0', hint: 'T' },
    { type: 'noun', deutsch: 'Laptop', chinese: '筆電', gender: 'der', plural: 'Laptops', Pl: '-s', countable: true, lesson: 'lesson 0' },
/**/{ type: 'noun', deutsch: 'Radiergummi', chinese: '橡皮擦', gender: 'der', plural: 'Radiergummis', Pl: '-s', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Buch', chinese: '書', gender: 'das', plural: 'Bücher', Pl: '-:er', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Heft', chinese: '筆記本', gender: 'das', plural: 'Hefte', Pl: '-e', countable: true, lesson: 'lesson 0' },
/**/{ type: 'noun', deutsch: 'Wort', chinese: '字', gender: 'das', plural: 'Wörter', Pl: '-:er', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Verb', chinese: '動詞', gender: 'das', plural: 'Verben', Pl: '-en', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Handy', chinese: '手機', gender: 'das', plural: 'Handys', Pl: '-s', countable: true, lesson: 'lesson 0' },
/**/{ type: 'noun', deutsch: 'Brötchen', chinese: '小麵包', gender: 'das', plural: 'Brötchen', Pl: '-', countable: true, lesson: 'lesson 0'},
    { type: 'noun', deutsch: 'Plakat', chinese: '佈告欄 看板', gender: 'das', plural: 'Plakate', Pl: '-e', countable: true, lesson: 'lesson 0' },    
    { type: 'noun', deutsch: 'Tafel', chinese: '黑板', gender: 'die', plural: 'Tafeln', Pl: '-n', countable: true, lesson: 'lesson 0'},
    { type: 'noun', deutsch: 'Tür', chinese: '門', gender: 'die', plural: 'Türen', Pl: '-en', countable: true, lesson: 'lesson 0'},
    { type: 'noun', deutsch: 'Uhr', chinese: '鐘', gender: 'die', plural: 'Uhren', Pl: '-en', countable: true, lesson: 'lesson 0'},
    { type: 'noun', deutsch: 'Tasche', chinese: '提袋 包包', gender: 'die', plural: 'Taschen', Pl: '-n', countable: true, lesson: 'lesson 0'},
    { type: 'noun', deutsch: 'Pause', chinese: '休息', gender: 'die', plural: 'Pausen', Pl: '-n', countable: true, lesson: 'lesson 0'},
    { type: 'noun', deutsch: 'Bitte', chinese: '請求', gender: 'die', plural: 'Bitten', Pl: '-n', countable: true, lesson: 'lesson 0'},
/**/{ type: 'noun', deutsch: 'Entschuldigung', chinese: '對不起', gender: 'die', plural: 'Entschuldigungen', Pl: '-en', countable: true, lesson: 'lesson 0'},
    { type: 'noun', deutsch: 'Ahnung', chinese: '概念 印象', gender: 'die', plural: 'Ahnungen', Pl: '-en', countable: true, lesson: 'lesson 0'},
    { type: 'noun', deutsch: 'Name', chinese: '姓名', gender: 'der', plural: 'Namen', Pl: '-n', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Vorname', chinese: '名(字)', gender: 'der', plural: 'Vornamen', Pl: '-n', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Nachname', chinese: '姓(氏)', gender: 'der', plural: 'Nachnamen', Pl: '-n', countable: true, lesson: 'lesson 1', hint: 'N' },
    { type: 'noun', deutsch: 'Familie', chinese: '家庭 家人', gender: 'die', plural: 'Familien', Pl: '-n', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Familienname', chinese: '姓(氏)', gender: 'der', plural: 'Familiennamen', Pl: '-n', countable: true, lesson: 'lesson 1', hint: 'F' },
    { type: 'noun', deutsch: 'Land', chinese: '國家', gender: 'das', plural: 'Länder', Pl: '-:er', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Nachbar', chinese: '鄰居', gender: 'der', plural: 'Nachbarn', Pl: '-n', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Nachbarland', chinese: '鄰國', gender: 'das', plural: 'Nachbarländer', Pl: '-:er', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Sprache', chinese: '語言', gender: 'die', plural: 'Sprachen', Pl: '-n', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Mutter', chinese: '母親', gender: 'die', plural: 'Mütter', Pl: '-:', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Muttersprache', chinese: '母語', gender: 'die', plural: 'Muttersprachen', Pl: '-n', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Ländername', chinese: '國名', gender: 'der', plural: 'Ländernamen', Pl: '-n', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Person', chinese: '人', gender: 'die', plural: 'Personen', Pl: '-en', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Tag', chinese: '天', gender: 'der', plural: 'Tage', Pl: '-e', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Sommer', chinese: '夏天', gender: 'der', countable: false, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Kurs', chinese: '課程', gender: 'der', plural: 'Kurse', Pl: '-e', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Sommerkurs', chinese: '夏季語言班', gender: 'der', plural: 'Sommerkurse', Pl: '-e', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Stadt', chinese: '城市', gender: 'die', plural: 'Städte', Pl: '-:e', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Satz', chinese: '句子 (定理/規則/沉澱物)', gender: 'der', plural: 'Sätze', Pl: '-:e', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Frage', chinese: '疑問', gender: 'die', plural: 'Fragen', Pl: '-n', countable: true, lesson: 'lesson 1' },
/**/{ type: 'noun', deutsch: 'Antwort', chinese: '回答', gender: 'die', plural: 'Antworten', Pl: '-en', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Satzfrage', chinese: '將直述句變成的問句', gender: 'die', plural: 'Satzfragen', Pl: '-n', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'W-Frage', chinese: '以疑問詞造的問句', gender: 'die', plural: 'W-Fragen', Pl: '-n', countable: true, lesson: 'lesson 1' },
/**/{ type: 'noun', deutsch: 'Wohnort', chinese: '住處', gender: 'der', plural: 'Wohnorte', Pl: '-e', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Zahl', chinese: '數字', gender: 'die', plural: 'Zahlen', Pl: '-en', countable: true, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Brief', chinese: '信', gender: 'der', plural: 'Briefe', Pl: '-e', countable: true, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Hund', chinese: '狗', gender: 'der', plural: 'Hunde', Pl: '-e', countable: true, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Zusteller', chinese: '郵差 快遞員', gender: 'der', plural: 'Zusteller', Pl: '-', countable: true, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Stress', chinese: '壓力', gender: 'der', countable: false, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Sport', chinese: '運動', gender: 'der', countable: false, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Garten', chinese: '花園', gender: 'der', plural: 'Gärten', Pl: '-:', countable: true, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Paket', chinese: '包裹', gender: 'das', plural: 'Pakete', Pl: '-e', countable: true, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Tempo', chinese: '節拍 速度', gender: 'das', plural: 'Tempi', Pl: '~pi', countable: true, lesson: 'lesson 2' },
/**/{ type: 'noun', deutsch: 'Problem', chinese: '課題 難題', gender: 'das', plural: 'Probleme', Pl: '-e', countable: true, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Arbeit', chinese: '工作', gender: 'die', plural: 'Arbeiten', Pl: '-en', countable: true, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Zeit', chinese: '時間(單數) 時段/時期/年代', gender: 'die', plural: 'Zeiten', Pl: '-en', countable: true, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Klingel', chinese: '(電)鈴', gender: 'die', plural: 'Klingeln', Pl: '-n', countable: true, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Adresse', chinese: '地址', gender: 'die', plural: 'Adressen', Pl: '-n', countable: true, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Absender', chinese: '寄件人', gender: 'der', plural: 'Absender', Pl: '-', countable: true, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Empfäger', chinese: '收件人', gender: 'der', plural: 'Empfäger', Pl: '-', countable: true, lesson: 'lesson 2' },
/**/{ type: 'noun', deutsch: 'Haus', chinese: '房屋 透天厝', gender: 'das', plural: 'Häuser', Pl: '-:er', countable: true, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Telefon', chinese: '電話', gender: 'das', plural: 'Telefone', Pl: '-e', countable: true, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Vorsicht', chinese: '小心 謹慎 注意', gender: 'die', countable: false, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Nummer', chinese: '號碼', gender: 'die', plural: 'Nummern', Pl: '-n', countable: true, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Hausnummer', chinese: '門牌號碼', gender: 'die', plural: 'Hausnummern', Pl: '-n', countable: true, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Handynummer', chinese: '手機號碼', gender: 'die', plural: 'Handynummern', Pl: '-n', countable: true, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Telefonnummer', chinese: '電話號碼', gender: 'die', plural: 'Telefonnummern', Pl: '-n', countable: true, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Straße', chinese: '街道', gender: 'die', plural: 'Straßen', Pl: '-n', countable: true, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Postleitzahl', chinese: '郵遞區號', gender: 'die', plural: 'Postleitzahlen', Pl: '-en', countable: true, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Lehrer', chinese: '老師 教師', gender: 'der', plural: 'Lehrer', Pl: '-', countable: true, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Lehrerin', chinese: '女老師', gender: 'die', plural: 'Lehrerinnen', Pl: '-nen', countable: true, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Morgen', chinese: '早晨', gender: 'der', plural: 'Morgen', Pl: '-', countable: true, lesson: 'lesson 2' },
/**/{ type: 'noun', deutsch: 'Briefkasten', chinese: '郵筒', gender: 'der', plural: 'Briefkästen', Pl: '-:', countable: true, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Partner', chinese: '伴侶 同伴', gender: 'der', plural: 'Partner', Pl: '-', countable: true, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Computer', chinese: '電腦', gender: 'der', plural: 'Computer', Pl: '-', countable: true, lesson: 'lesson 2' },
/**/{ type: 'noun', deutsch: 'Briefmarke', chinese: '郵票', gender: 'die', plural: 'Briefmarken', Pl: '-n', countable: true, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Postkarte', chinese: '明信片', gender: 'die', plural: 'Postkarten', Pl: '-n', countable: true, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Nachricht', chinese: '訊息 新聞', gender: 'die', plural: 'Nachrichten', Pl: '-en', countable: true, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Herr', chinese: 'O先生(稱呼) 主人', gender: 'der', plural: 'Herren', Pl: '-en', countable: true, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Frau', chinese: 'O小姐/女士 女人 人妻', gender: 'die', plural: 'Frauen', Pl: '-en', countable: true, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Fußball', chinese: '足球(運動)', gender: 'der', countable: false, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Verein', chinese: '協會 社團 聯盟', gender: 'der', plural: 'Vereine', Pl: '-e', countable: true, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Fußballverein', chinese: '足球協會', gender: 'der', plural: 'Fußballvereine', Pl: '-e', countable: true, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Profi', chinese: '職業運動員', gender: 'der', plural: 'Profis', Pl: '-s', countable: true, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Profi-Fußball', chinese: '職業足球', gender: 'der', countable: false, lesson: 'lesson 2' },
/**/{ type: 'noun', deutsch: 'Torwart', chinese: '守門員', gender: 'der', plural: 'Torwarte', Pl: '-e', countable: true, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Trainer', chinese: '教練', gender: 'der', plural: 'Trainer', Pl: '-', countable: true, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Spieler', chinese: '球員 參賽者 表演者', gender: 'der', plural: 'Spieler', Pl: '-', countable: true, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Nationalspieler', chinese: '國手', gender: 'der', plural: 'Nationalspieler', Pl: '-', countable: true, lesson: 'lesson 2' },
/**/{ type: 'noun', deutsch: 'Dorf', chinese: '鄉村', gender: 'das', plural: 'Dörfer', Pl: '-:er', countable: true, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Training', chinese: '訓練', gender: 'das', countable: false, lesson: 'lesson 2' },
/**/{ type: 'noun', deutsch: 'Mannschaft', chinese: '球隊 機組人員', gender: 'die', plural: 'Mannschaften', Pl: '-en', countable: true, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Profimannschaft', chinese: '職業球隊', gender: 'die', plural: 'Profimannschaften', Pl: '-en', countable: true, lesson: 'lesson 2' },
    { type: 'noun', deutsch: 'Heimat', chinese: '故鄉 祖國', gender: 'die', plural: 'Heimat', Pl: '-en', countable: true, lesson: 'lesson 2' },

    // 動詞
    //{ type: 'verb', infinitiv: '', ich: '', du: '', er: '', wir: '', ihr: '', sie: '', chinese: '', lesson: '', hint: '' },
/**/{ type: 'verb', infinitiv: 'hören', ich: 'höre', du: 'hörst', er: 'hört', wir: 'hören', ihr: 'hört', sie: 'hören', chinese: '聽', lesson: 'lesson 0' },
    { type: 'verb', infinitiv: 'lesen', ich: 'lese', du: 'liest', er: 'liest', wir: 'lesen', ihr: 'lest', sie: 'lesen', chinese: '讀', lesson: 'lesson 0' },
/**/{ type: 'verb', infinitiv: 'schreiben', ich: 'schreibe', du: 'schreibst', er: 'schreibt', wir: 'schreiben', ihr: 'schreibt', sie: 'schreiben', chinese: '寫', lesson: 'lesson 0' },
    { type: 'verb', infinitiv: 'können', ich: 'kann', du: 'kannst', er: 'kann', wir: 'können', ihr: 'könnt', sie: 'können', chinese: '可以 能夠', lesson: 'lesson 0' },
/**/{ type: 'verb', infinitiv: 'verstehen', ich: 'verstehe', du: 'verstehst', er: 'versteht', wir: 'verstehen', ihr: 'versteht', sie: 'verstehen', chinese: '懂 明瞭', lesson: 'lesson 0' },
/**/{ type: 'verb', infinitiv: 'buchstabieren', ich: 'buchstabiere', du: 'buchstabierst', er: 'buchstabiert', wir: 'buchstabieren', ihr: 'buchstabiert', sie: 'buchstabieren', chinese: '拚字(母)', lesson: 'lesson 0' },
    { type: 'verb', infinitiv: 'wiederholen', ich: 'wiederhole', du: 'wiederholst', er: 'wiederholt', wir: 'wiederholen', ihr: 'wiederholt', sie: 'wiederholen', chinese: '重複', lesson: 'lesson 0' },
    { type: 'verb', infinitiv: 'sein', ich: 'bin', du: 'bist', er: 'ist', wir: 'sind', ihr: 'seid', sie: 'sind', chinese: '是', lesson: 'lesson 1' },
    { type: 'verb', infinitiv: 'leben', ich: 'lebe', du: 'lebst', er: 'lebt', wir: 'leben', ihr: 'lebt', sie: 'leben', chinese: '住', lesson: 'lesson 1', hint: 'l' },
    { type: 'verb', infinitiv: 'wohnen', ich: 'wohne', du: 'wohnst', er: 'wohnt', wir: 'wohnen', ihr: 'wohnt', sie: 'wohnen', chinese: '住', lesson: 'lesson 1', hint: 'w' },
    { type: 'verb', infinitiv: 'machen', ich: 'mache', du: 'machst', er: 'macht', wir: 'machen', ihr: 'macht', sie: 'machen', chinese: '做...', lesson: 'lesson 1' },
    { type: 'verb', infinitiv: 'lernen', ich: 'lerne', du: 'lernst', er: 'lernt', wir: 'lernen', ihr: 'lernt', sie: 'lernen', chinese: '學習', lesson: 'lesson 1' },
    { type: 'verb', infinitiv: 'heißen', ich: 'heiße', du: 'heißt', er: 'heißt', wir: 'heißen', ihr: 'heißt', sie: 'heißen', chinese: '叫做 稱作', lesson: 'lesson 1' },
    { type: 'verb', infinitiv: 'kommen', ich: 'komme', du: 'kommst', er: 'kommt', wir: 'kommen', ihr: 'kommt', sie: 'kommen', chinese: '來(自)', lesson: 'lesson 1' },
    { type: 'verb', infinitiv: 'sprechen', ich: 'spreche', du: 'sprichst', er: 'spricht', wir: 'sprechen', ihr: 'sprecht', sie: 'sprechen', chinese: '說(語言)(能力)', lesson: 'lesson 1' },
    { type: 'verb', infinitiv: 'sagen', ich: 'sage', du: 'sagst', er: 'sagt', wir: 'sagen', ihr: 'sagt', sie: 'sagen', chinese: '說...(內容)', lesson: 'lesson 2' },
/**/{ type: 'verb', infinitiv: 'mögen', ich: 'mag', du: 'magst', er: 'mag', wir: 'mögen', ihr: 'mögt', sie: 'mögen', chinese: '喜歡', lesson: 'lesson 2' },
/**/{ type: 'verb', infinitiv: 'haben', ich: 'habe', du: 'hast', er: 'hat', wir: 'haben', ihr: 'habt', sie: 'haben', chinese: '有...', lesson: 'lesson 2' },
    { type: 'verb', infinitiv: 'bekommen', ich: 'bekomme', du: 'bekommst', er: 'bekommt', wir: 'bekommen', ihr: 'bekommt', sie: 'bekommen', chinese: '得到', lesson: 'lesson 2' },
    { type: 'verb', infinitiv: 'spielen', ich: 'spiele', du: 'spielst', er: 'spielt', wir: 'spielen', ihr: 'spielt', sie: 'spielen', chinese: '踢(球) 演奏(樂器) 玩(遊戲) 下(棋)', lesson: 'lesson 2' },

    // 形容詞
    //{ type: 'adjective', deutsch: '', chinese: '', lesson: '' },
    { type: 'adjective', deutsch: 'klar', chinese: '清楚的 當然', lesson: 'lesson 0' },
    { type: 'adjective', deutsch: 'gut', chinese: '好的', lesson: 'lesson 1' },
    { type: 'adjective', deutsch: 'schlecht', chinese: '糟的', lesson: 'lesson 1' },
    { type: 'adjective', deutsch: 'böse', chinese: '惡的', lesson: 'lesson 1' },
    { type: 'adjective', deutsch: 'groß', chinese: '高的 大的', lesson: 'lesson 1' },
    { type: 'adjective', deutsch: 'klein', chinese: '矮的 小的', lesson: 'lesson 1' },
/**/{ type: 'adjective', deutsch: 'schön', chinese: '美的 美好的', lesson: 'lesson 1' },
/**/{ type: 'adjective', deutsch: 'süß', chinese: '甜的 甜美的', lesson: 'lesson 1' },
    { type: 'adjective', deutsch: 'cool', chinese: '酷 有趣的', lesson: 'lesson 1' },
    { type: 'adjective', deutsch: 'viel', chinese: '多', lesson: 'lesson 1' },
    { type: 'adjective', deutsch: 'wenig', chinese: '少', lesson: 'lesson 1' },
    { type: 'adjective', deutsch: 'international', chinese: '國際的', lesson: 'lesson 1' },
    { type: 'adjective', deutsch: 'deutsch', chinese: '德國(人)的 德語的 德國文化的', lesson: 'lesson 2' },
    { type: 'adjective', deutsch: 'sorry', chinese: '對不起 可惜 遺憾', lesson: 'lesson 2' },
    { type: 'adjective', deutsch: 'typisch', chinese: '典型 具代表性的', lesson: 'lesson 2' },
/**/{ type: 'adjective', deutsch: 'herzlich', chinese: '(形容詞)熱烈 衷心的\n(副詞)非常 很', lesson: 'lesson 2' },
    { type: 'adjective', deutsch: 'willkommen', chinese: '受人歡迎 令人高興的', lesson: 'lesson 2' },

    // 副詞
    //{ type: 'adverb', deutsch: '', chinese: '', lesson: '' },
    { type: 'adverb', deutsch: 'gerne', chinese: '樂意地 喜歡地', lesson: 'lesson 0', hint: '-e' },
    { type: 'adverb', deutsch: 'gern', chinese: '樂意地 喜歡地', lesson: 'lesson 0', hint: '-n' },
    { type: 'adverb', deutsch: 'super', chinese: '讚 棒地', lesson: 'lesson 1', hint: '副詞' },
    { type: 'adverb', deutsch: 'nicht', chinese: '(否定)', lesson: 'lesson 1' },
    { type: 'adverb', deutsch: 'noch', chinese: '仍然', lesson: 'lesson 1' },
    { type: 'adverb', deutsch: 'jetzt', chinese: '現在', lesson: 'lesson 1' },
    { type: 'adverb', deutsch: 'auch', chinese: '也', lesson: 'lesson 1' },
    { type: 'adverb', deutsch: 'so', chinese: '如此 這樣', lesson: 'lesson 2' },
    { type: 'adverb', deutsch: 'da', chinese: '在場 (這兒 那兒)', lesson: 'lesson 2' },
    { type: 'adverb', deutsch: 'denn', chinese: '究竟 到底(使語氣友善)', lesson: 'lesson 2' },
    { type: 'adverb', deutsch: 'oft', chinese: '常常 時常', lesson: 'lesson 2' },
    { type: 'adverb', deutsch: 'nur', chinese: '僅 只', lesson: 'lesson 2' },

    // 疑問詞
    //{ type: 'question', deutsch: '', chinese: '', lesson: '' },
    { type: 'question', deutsch: 'wo', chinese: '哪裡', lesson: 'lesson 1' },
    { type: 'question', deutsch: 'was', chinese: '什麼', lesson: 'lesson 1' },
    { type: 'question', deutsch: 'wie', chinese: '如何', lesson: 'lesson 1' },
    { type: 'question', deutsch: 'wer', chinese: '誰', lesson: 'lesson 1' },
    { type: 'question', deutsch: 'woher', chinese: '從哪裡來', lesson: 'lesson 1' },
    { type: 'question', deutsch: 'welche', chinese: '哪一個(些)', lesson: 'lesson 1' },

    // 其他(人稱代名詞 介係詞 連接詞 所有格冠詞 片語)
    { type: 'other', deutsch: 'man', chinese: '任一人 某人', lesson: 'lesson 0' },
    { type: 'other', deutsch: 'ich', chinese: '我', lesson: 'lesson 1' },
    { type: 'other', deutsch: 'du', chinese: '你', lesson: 'lesson 1' },
    { type: 'other', deutsch: 'er', chinese: '他', lesson: 'lesson 1' },
    { type: 'other', deutsch: 'es', chinese: '它', lesson: 'lesson 1' },
    { type: 'other', deutsch: 'sie', chinese: '她/他們/您(們)', lesson: 'lesson 1' },
    { type: 'other', deutsch: 'wir', chinese: '我們', lesson: 'lesson 1' },
    { type: 'other', deutsch: 'ihr', chinese: '你們', lesson: 'lesson 1' },
    { type: 'other', deutsch: 'in', chinese: '在...內', lesson: 'lesson 1' },
    { type: 'other', deutsch: 'und', chinese: '和 且', lesson: 'lesson 1' },
    { type: 'other', deutsch: 'mein', chinese: '我的', lesson: 'lesson 1' },
    { type: 'other', deutsch: 'dein', chinese: '你的', lesson: 'lesson 1' },
    { type: 'other', deutsch: 'Ihr', chinese: '您的', lesson: 'lesson 1' },
    { type: 'other', deutsch: 'aus', chinese: '來自於(籍貫)', lesson: 'lesson 1' },
    { type: 'other', deutsch: 'ein bisschen', chinese: '一些些', lesson: 'lesson 1' },
    { type: 'other', deutsch: 'aber', chinese: '但 然而', lesson: 'lesson 1' },
    { type: 'other', deutsch: 'auf', chinese: '以...方式', lesson: 'lesson 1' },
    { type: 'other', deutsch: 'für', chinese: '對...而言 為了...', lesson: 'lesson 2' },
    { type: 'other', deutsch: 'sein', chinese: '他的', lesson: 'lesson 2' },
    { type: 'other', deutsch: 'oder', chinese: '或', lesson: 'lesson 2' },
    { type: 'other', deutsch: 'bei', chinese: '在...附近', lesson: 'lesson 2' },
    { type: 'other', deutsch: 'seit', chinese: '自...至今', lesson: 'lesson 2' },
    { type: 'other', deutsch: 'es gibt', chinese: '有... (there is/are)', lesson: 'lesson 2' },

    // 片語
    //{ type: 'phrase', deutsch: '', chinese: '', lesson: '' },
    { type: 'phrase', deutsch: 'Danke', chinese: '謝謝!', lesson: 'lesson 0' },
    { type: 'phrase', deutsch: 'Bitte', chinese: '不客氣!', lesson: 'lesson 0' },
    { type: 'phrase', deutsch: 'Keine Ahnung', chinese: '不知道!', lesson: 'lesson 0' },
    { type: 'phrase', deutsch: 'Entschuldigung', chinese: '對不起!', lesson: 'lesson 0' },
    { type: 'phrase', deutsch: 'Na klar', chinese: '那當然!', lesson: 'lesson 0' },
    { type: 'phrase', deutsch: 'Kein Problem', chinese: '沒問題!', lesson: 'lesson 0' },
    { type: 'phrase', deutsch: 'Guten Morgen', chinese: '早安!', lesson: 'lesson 0' },
    { type: 'phrase', deutsch: 'Wie bitte', chinese: '你說什麼? 請再說一遍', lesson: 'lesson 0' },
    { type: 'phrase', deutsch: 'Guten Tag', chinese: '您好! 日安!', lesson: 'lesson 1' },
    { type: 'phrase', deutsch: 'Tschüss', chinese: '再見!', lesson: 'lesson 1', hint: '-ss' },
    { type: 'phrase', deutsch: 'Tschüs', chinese: '再見!', lesson: 'lesson 1', hint: '-s' },

    // 國家 語言 城市(名詞)
    { type: 'country', deutsch: 'Deutschland', chinese: '德國', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Deutsch', chinese: '德語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Spanien', chinese: '西班牙', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Spanisch', chinese: '西班牙語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Japan', chinese: '日本', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Japanisch', chinese: '日語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Indonesien', chinese: '印尼', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Indonesisch', chinese: '印尼語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'England', chinese: '英國', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Englisch', chinese: '英語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'die USA', chinese: '美國', countable: true, plural: true, lesson: 'lesson 1' },
/**/{ type: 'country', deutsch: 'die Niederlande', chinese: '荷蘭', countable: true, plural: true, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Niederländisch', chinese: '荷蘭語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'China', chinese: '中國', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Chinesisch', chinese: '中文', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Kamerun', chinese: '喀麥隆', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Kamtok', chinese: '皮欽語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Vietnam', chinese: '越南', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Vietnamesisch', chinese: '越南語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Russland', chinese: '俄羅斯', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Russisch', chinese: '俄語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Italien', chinese: '義大利', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Italienisch', chinese: '義大利語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Arabien', chinese: '阿拉伯', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Arabisch', chinese: '阿拉伯語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Norwegen', chinese: '挪威', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Norwegisch', chinese: '挪威語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Tschechien', chinese: '捷克', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Tschechisch', chinese: '捷克語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Polen', chinese: '波蘭', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Polnisch', chinese: '波蘭語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Dänemark', chinese: '丹麥', countable: false, lesson: 'lesson 1' },
/**/{ type: 'country', deutsch: 'Dänisch', chinese: '丹麥語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'die Schweiz', chinese: '瑞士', countable: true, plural: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Frankreich', chinese: '法國', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Französisch', chinese: '法語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'der Iran', chinese: '伊朗', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Farsi', chinese: '波斯語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'die Türkei', chinese: '土耳其', countable: true, plural: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Türkisch', chinese: '土耳其語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Portugal', chinese: '葡萄牙', countable: false, lesson: 'lesson 1' },
/**/{ type: 'country', deutsch: 'Portugiesisch', chinese: '葡萄牙語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Brasilien', chinese: '巴西', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Thailand', chinese: '泰國', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Thai', chinese: '泰語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Neuseeland', chinese: '紐西蘭', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Bulgarien', chinese: '保加利亞', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Österreich', chinese: '奧地利', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Luxemburg', chinese: '盧森堡', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Schweden', chinese: '瑞典', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Schwedisch', chinese: '瑞典語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Finnland', chinese: '芬蘭', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Finnisch', chinese: '芬蘭語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Berlin', chinese: '柏林', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Belgien', chinese: '比利時', countable: false, lesson: 'lesson 2' },
    { type: 'country', deutsch: 'Syrien', chinese: '敘利亞', countable: false, lesson: 'lesson 2' },
    { type: 'country', deutsch: 'Argentinien', chinese: '阿根廷', countable: false, lesson: 'lesson 2' }
]);