// 特殊字符 Ä ä Ö ö Ü ü ẞ ß
const vocabList = [
    // 名詞
    //{ type: 'noun', deutsch: '', chinese: '', gender: '', plural: '', Pl: '', countable: false/true, lesson: '', hint: '' },
    { type: 'noun', deutsch: 'Kursraum', chinese: '教室', gender: 'der', plural: 'Kursräume', Pl: '-:e', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Tisch', chinese: '桌', gender: 'der', plural: 'Tische', Pl: '-e', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Stuhl', chinese: '椅', gender: 'der', plural: 'Stühle', Pl: '-:e', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Kuli', chinese: '原子筆', gender: 'der', plural: 'Kulis', Pl: '-s', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Stift', chinese: '筆', gender: 'der', plural: 'Stifte', Pl: '-e', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Bleistift', chinese: '鉛筆', gender: 'der', plural: 'Bleistifte', Pl: '-e', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Gegenstand', chinese: '東西 物件', gender: 'der', plural: 'Gegenstände', Pl: '-:e', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Text', chinese: '文章', gender: 'der', plural: 'Texte', Pl: '-e', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Marker', chinese: '馬克筆', gender: 'der', plural: 'Marker', Pl: '-', countable: true, lesson: 'lesson 0', hint: 'M' },
    { type: 'noun', deutsch: 'Textmarker', chinese: '馬克筆', gender: 'der', plural: 'Textmarker', Pl: '-', countable: true, lesson: 'lesson 0', hint: 'T' },
    { type: 'noun', deutsch: 'Laptop', chinese: '筆電', gender: 'der', plural: 'Laptops', Pl: '-s', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Kaffee', chinese: '咖啡', gender: 'der', plural: 'Kaffees', Pl: '-s', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Tee', chinese: '茶', gender: 'der', plural: 'Tees', Pl: '-s', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Radiergummi', chinese: '橡皮擦', gender: 'der', plural: 'Radiergummis', Pl: '-s', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Buch', chinese: '書', gender: 'das', plural: 'Bücher', Pl: '-:er', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Wort', chinese: '字', gender: 'das', plural: 'Wörter', Pl: '-:er', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Handy', chinese: '手機', gender: 'das', plural: 'Handys', Pl: '-s', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Heft', chinese: '筆記本', gender: 'das', plural: 'Hefte', Pl: '-e', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Plakat', chinese: '佈告欄 看板', gender: 'das', plural: 'Plakate', Pl: '-e', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Brötchen', chinese: '小麵包', gender: 'das', plural: 'Brötchen', Pl: '-', countable: true, lesson: 'lesson 0'},
    { type: 'noun', deutsch: 'Tafel', chinese: '黑板', gender: 'die', plural: 'Tafeln', Pl: '-n', countable: true, lesson: 'lesson 0'},
    { type: 'noun', deutsch: 'Tür', chinese: '門', gender: 'die', plural: 'Türen', Pl: '-en', countable: true, lesson: 'lesson 0'},
    { type: 'noun', deutsch: 'Uhr', chinese: '鐘錶', gender: 'die', plural: 'Uhren', Pl: '-en', countable: true, lesson: 'lesson 0'},
    { type: 'noun', deutsch: 'Tasche', chinese: '提袋 包包', gender: 'die', plural: 'Taschen', Pl: '-n', countable: true, lesson: 'lesson 0'},
    { type: 'noun', deutsch: 'Pause', chinese: '休息', gender: 'die', plural: 'Pausen', Pl: '-n', countable: true, lesson: 'lesson 0'},
    
    { type: 'noun', deutsch: 'Name', chinese: '姓名', gender: 'der', plural: 'Namen', Pl: '-n', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Vorname', chinese: '名(字)', gender: 'der', plural: 'Vornamen', Pl: '-n', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Nachname', chinese: '姓(氏)', gender: 'der', plural: 'Nachnamen', Pl: '-n', countable: true, lesson: 'lesson 1', hint: 'N' },
    { type: 'noun', deutsch: 'Familie', chinese: '家庭 家人', gender: 'die', plural: 'Familie', Pl: '-n', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Familienname', chinese: '姓(氏)', gender: 'der', plural: 'Familiennamen', Pl: '-n', countable: true, lesson: 'lesson 1', hint: 'F' },
    { type: 'noun', deutsch: 'Land', chinese: '國家', gender: 'das', plural: 'Länder', Pl: '-:er', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Nachbar', chinese: '鄰居', gender: 'der', plural: 'Nachbarn', Pl: '-n', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Nachbarland', chinese: '鄰國', gender: 'das', plural: 'Nachbarländer', Pl: '-:er', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Sprache', chinese: '語言', gender: 'die', plural: 'Sprachen', Pl: '-n', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Mutter', chinese: '母親', gender: 'die', plural: 'Mütter', Pl: '-:', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Muttersprache', chinese: '母語', gender: 'die', plural: 'Muttersprachen', Pl: '-n', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Ländername', chinese: '國名', gender: 'der', plural: 'Ländernamen', Pl: '-n', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Person', chinese: '國家', gender: 'die', plural: 'Personen', Pl: '-en', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Tag', chinese: '天', gender: 'der', plural: 'Tage', Pl: '-e', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Sommer', chinese: '夏天', gender: 'der', countable: false, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Kurs', chinese: '課程', gender: 'der', plural: 'Kurse', Pl: '-e', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Sommerkurs', chinese: '夏季語言班', gender: 'der', plural: 'Sommerkurse', Pl: '-e', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Stadt', chinese: '城市', gender: 'der', plural: 'Städte', Pl: '-:e', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Satz', chinese: '句子 (定理/規則/沉澱物)', gender: 'der', plural: 'Sätze', Pl: '-:e', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Frage', chinese: '疑問', gender: 'die', plural: 'Fragen', Pl: '-n', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Antwort', chinese: '回答', gender: 'die', plural: 'Antworten', Pl: '-en', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Satzfrage', chinese: '將直述句變成的問句', gender: 'die', plural: 'Satzfragen', Pl: '-n', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'W-frage', chinese: '以疑問詞造的問句', gender: 'die', plural: 'W-fragen', Pl: '-n', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Wohnort', chinese: '住處', gender: 'die', plural: 'Wohnorte', Pl: '-e', countable: true, lesson: 'lesson 1' },

    // 動詞
    //{ type: 'verb', infinitiv: '', ich: '', du: '', er: '', wir: '', ihr: '', sie: '', chinese: '', lesson: '', hint: '' },
    { type: 'verb', infinitiv: 'hören', ich: 'höre', du: 'hörst', er: 'hört', wir: 'hören', ihr: 'hört', sie: 'hören', chinese: '聽', lesson: 'lesson 0' },
    { type: 'verb', infinitiv: 'lesen', ich: 'lese', du: 'liest', er: 'liest', wir: 'lesen', ihr: 'lest', sie: 'lesen', chinese: '讀', lesson: 'lesson 0' },
    { type: 'verb', infinitiv: 'schreiben', ich: 'schreibe', du: 'schreibst', er: 'schreibt', wir: 'schreiben', ihr: 'schreibt', sie: 'schreiben', chinese: '寫', lesson: 'lesson 0' },
    { type: 'verb', infinitiv: 'können', ich: 'kann', du: 'kannst', er: 'kann', wir: 'können', ihr: 'könnt', sie: 'können', chinese: '可以 能夠', lesson: 'lesson 0' },
    { type: 'verb', infinitiv: 'buchstabieren', ich: 'buchstabiere', du: 'buchstabierst', er: 'buchstabiert', wir: 'buchstabieren', ihr: 'buchstabiert', sie: 'buchstabieren', chinese: '拚字(母)', lesson: 'lesson 0' },
    { type: 'verb', infinitiv: 'wiederholen', ich: 'wiederhole', du: 'wiederholst', er: 'wiederholt', wir: 'wiederholen', ihr: 'wiederholt', sie: 'wiederholen', chinese: '重複', lesson: 'lesson 0' },
    { type: 'verb', infinitiv: 'verstehen', ich: 'verstehe', du: 'verstehst', er: 'versteht', wir: 'verstehen', ihr: 'versteht', sie: 'verstehen', chinese: '明瞭 懂', lesson: 'lesson 0' },

    { type: 'verb', infinitiv: 'sein', ich: 'bin', du: 'bist', er: 'ist', wir: 'sind', ihr: 'seid', sie: 'sind', chinese: '是', lesson: 'lesson 1' },
    { type: 'verb', infinitiv: 'leben', ich: 'lebe', du: 'lebst', er: 'lebt', wir: 'leben', ihr: 'lebt', sie: 'leben', chinese: '住', lesson: 'lesson 1', hint: 'l' },
    { type: 'verb', infinitiv: 'wohnen', ich: 'wohne', du: 'wohnst', er: 'wohnt', wir: 'wohnen', ihr: 'wohnt', sie: 'wohnen', chinese: '住', lesson: 'lesson 1', hint: 'w' },
    { type: 'verb', infinitiv: 'machen', ich: 'mache', du: 'machst', er: 'macht', wir: 'machen', ihr: 'macht', sie: 'machen', chinese: '做...', lesson: 'lesson 1' },
    { type: 'verb', infinitiv: 'lernen', ich: 'lerne', du: 'lernst', er: 'lernt', wir: 'lernen', ihr: 'lernt', sie: 'lernen', chinese: '做...', lesson: 'lesson 1' },
    { type: 'verb', infinitiv: 'heißen', ich: 'heiße', du: 'heißt', er: 'heißt', wir: 'heißen', ihr: 'heißt', sie: 'heißen', chinese: '叫做 稱作', lesson: 'lesson 1' },
    { type: 'verb', infinitiv: 'kommen', ich: 'komme', du: 'kommst', er: 'kommt', wir: 'kommen', ihr: 'kommt', sie: 'kommen', chinese: '來(自)', lesson: 'lesson 1' },
    { type: 'verb', infinitiv: 'sprechen', ich: 'spreche', du: 'sprichst', er: 'spricht', wir: 'sprechen', ihr: 'sprecht', sie: 'sprechen', chinese: '說(語言)(能力)', lesson: 'lesson 1' },

    { type: 'verb', infinitiv: 'bekommen', ich: 'bekomme', du: 'bekommst', er: 'bekommt', wir: 'bekommen', ihr: 'bekommt', sie: 'bekommen', chinese: '得到', lesson: 'lesson 2' },

    // 形容詞
    //{ type: 'adjective', deutsch: '', chinese: '', lesson: '' },
    { type: 'adjective', deutsch: 'klar', chinese: '清楚的', lesson: 'lesson 0' },

    { type: 'adjective', deutsch: 'gut', chinese: '好的', lesson: 'lesson 1' },
    { type: 'adjective', deutsch: 'schlecht', chinese: '糟的', lesson: 'lesson 1' },
    { type: 'adjective', deutsch: 'böse', chinese: '惡的', lesson: 'lesson 1' },
    { type: 'adjective', deutsch: 'groß', chinese: '高的 大的', lesson: 'lesson 1' },
    { type: 'adjective', deutsch: 'klein', chinese: '矮的 小的', lesson: 'lesson 1' },
    { type: 'adjective', deutsch: 'schön', chinese: '美的 美好的', lesson: 'lesson 1' },
    { type: 'adjective', deutsch: 'süß', chinese: '甜的 甜美的', lesson: 'lesson 1' },
    { type: 'adjective', deutsch: 'cool', chinese: '酷 有趣的', lesson: 'lesson 1' },
    { type: 'adjective', deutsch: 'viel', chinese: '多', lesson: 'lesson 1' },
    { type: 'adjective', deutsch: 'wenig', chinese: '少', lesson: 'lesson 1' },
    { type: 'adjective', deutsch: 'international', chinese: '國際的', lesson: 'lesson 1' },

    // 副詞
    //{ type: 'adverb', deutsch: '', chinese: '', lesson: '' },
    { type: 'adverb', deutsch: 'gerne', chinese: '樂意地 喜歡地', lesson: 'lesson 0', hint: '-e'  },
    { type: 'adverb', deutsch: 'gern', chinese: '樂意地 喜歡地', lesson: 'lesson 0'},

    { type: 'adverb', deutsch: 'hier', chinese: '這裡', lesson: 'lesson 1' },
    { type: 'adverb', deutsch: 'dort', chinese: '那裡', lesson: 'lesson 1' },
    { type: 'adverb', deutsch: 'super', chinese: '讚 棒地', lesson: 'lesson 1' },
    { type: 'adverb', deutsch: 'nicht', chinese: '(否定)', lesson: 'lesson 1' },
    { type: 'adverb', deutsch: 'nach', chinese: '仍然', lesson: 'lesson 1' },
    { type: 'adverb', deutsch: 'jetzt', chinese: '現在', lesson: 'lesson 1' },
    { type: 'adverb', deutsch: 'auch', chinese: '也', lesson: 'lesson 1' },

    // 疑問詞
    //{ type: 'question', deutsch: '', chinese: '', lesson: '' },
    { type: 'question', deutsch: 'wo', chinese: '哪裡', lesson: 'lesson 1' },
    { type: 'question', deutsch: 'was', chinese: '什麼', lesson: 'lesson 1' },
    { type: 'question', deutsch: 'wie', chinese: '如何', lesson: 'lesson 1' },
    { type: 'question', deutsch: 'wer', chinese: '誰', lesson: 'lesson 1' },
    { type: 'question', deutsch: 'woher', chinese: '從哪裡來', lesson: 'lesson 1' },
    { type: 'question', deutsch: 'welche', chinese: '哪一個(些)', lesson: 'lesson 1' },

    // 其他(人稱代名詞 介係詞 連接詞 所有格冠詞)
    { type: 'other', deutsch: 'ich', chinese: '我', lesson: 'lesson 1' },
    { type: 'other', deutsch: 'du', chinese: '你', lesson: 'lesson 1' },
    { type: 'other', deutsch: 'er', chinese: '他', lesson: 'lesson 1' },
    { type: 'other', deutsch: 'es', chinese: '它', lesson: 'lesson 1' },
    { type: 'other', deutsch: 'sie', chinese: '她/他們/您(們)', lesson: 'lesson 1' },
    { type: 'other', deutsch: 'wir', chinese: '我們', lesson: 'lesson 1' },
    { type: 'other', deutsch: 'ihr', chinese: '你們', lesson: 'lesson 1' },
    { type: 'other', deutsch: 'in', chinese: '在...內', lesson: 'lesson 1' },
    { type: 'other', deutsch: 'und', chinese: '和 且', lesson: 'lesson 1' },
    { type: 'other', deutsch: 'mein', chinese: '我的', lesson: 'lesson 1' },
    { type: 'other', deutsch: 'dein', chinese: '你的', lesson: 'lesson 1' },
    { type: 'other', deutsch: 'Ihr', chinese: '您的', lesson: 'lesson 1' },
    { type: 'other', deutsch: 'aus', chinese: '來自於(籍貫)', lesson: 'lesson 1' },
    { type: 'other', deutsch: 'aber', chinese: '但 然而', lesson: 'lesson 1' },
    { type: 'other', deutsch: 'auf', chinese: '以...方式', lesson: 'lesson 1' },

    { type: 'other', deutsch: 'sein', chinese: '他的', lesson: 'lesson 2' },

    // 國家 語言 城市(名詞)
    { type: 'country', deutsch: 'Deutschland', chinese: '德國', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Deutsch', chinese: '德語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Spanien', chinese: '西班牙', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Spanisch', chinese: '西班牙語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Japan', chinese: '日本', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Japanisch', chinese: '日語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Indonesien', chinese: '印尼', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Indonesisch', chinese: '印尼語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'England', chinese: '英國', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Englisch', chinese: '英語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'die U.S.A.', chinese: '美國', countable: true, plural:true, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'die Niederlande', chinese: '荷蘭', countable: true, plural:true, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Niederländisch', chinese: '荷蘭語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'China', chinese: '中國', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Chinesisch', chinese: '中文', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Kamerun', chinese: '喀麥隆', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Kamtok', chinese: '皮欽語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Vietnam', chinese: '越南', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Vietnamesisch', chinese: '越南語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Russland', chinese: '俄羅斯', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Russisch', chinese: '俄語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Italien', chinese: '義大利', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Italienisch', chinese: '義大利語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Arabien', chinese: '阿拉伯', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Arabisch', chinese: '阿拉伯語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Norwegen', chinese: '挪威', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Norwegisch', chinese: '挪威語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Tschechien', chinese: '捷克', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Tschechisch', chinese: '捷克語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Polen', chinese: '波蘭', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Polnisch', chinese: '波蘭語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Dänemark', chinese: '丹麥', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Dänisch', chinese: '丹麥語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'die Schweiz', chinese: '瑞士', countable: true, plural:false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Frankreich', chinese: '法國', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Französisch', chinese: '法語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'der Iran', chinese: '伊朗', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Farsi', chinese: '波斯語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'die Tütkei', chinese: '土耳其', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Türkisch', chinese: '土耳其語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Portugal', chinese: '葡萄牙', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Portugiesisch', chinese: '葡萄牙語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Brasilien', chinese: '巴西', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Thailand', chinese: '泰國', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Thai', chinese: '泰語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Neuseeland', chinese: '紐西蘭', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'bulgarien', chinese: '保加利亞', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Österreich', chinese: '奧地利', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Luxemburg', chinese: '盧森堡', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Schweden', chinese: '瑞典', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Schwedisch', chinese: '瑞典語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Finnland', chinese: '芬蘭', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Finnisch', chinese: '芬蘭語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Belgien', chinese: '比利時', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Berlin', chinese: '柏林', countable: false, lesson: 'lesson 1' },
    
];